### ISSUE TITLE
No product_names available in datacube_viewer nb

### ISSUE THREAD

**Issue by patrickmuston1** [EY-Data-Science-Program/2020-bushfire-challenge#4]
@alexgleith Jorge and I are receiving the error below when running the "datacube_viewer" notebook when running in fresh deployments in Azure. Not sure when the error started, is this an indexing issue?

`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-04ac22220618> in <module>
     14         'fillOpacity': 0.05,
     15         'color': 'teal',
---> 16         'weight': 0.7
     17     }
     18 )

/env/lib/python3.6/site-packages/odc/ui/_dc_explore.py in __init__(self, dc, time, products, zoom, center, height, width, style)
     55                                     center=center,
     56                                     height=height,
---> 57                                     width=width)
     58         self._state = state
     59         self._gui = gui

/env/lib/python3.6/site-packages/odc/ui/_dc_explore.py in _build_ui(self, product_names, time, zoom, center, height, width)
    126 
    127         state = SimpleNamespace(time=time,
--> 128                                 product=product_names[0],
    129                                 count=0,
    130                                 bounds=None)

IndexError: list index out of range`

**Comment by alexgleith** [comment]
Hey @patrickmuston1 has indexing completed? I looked at this in the AWS deployment and it worked ok.

Can I get some Azure credits to test with?

Also, on the command line in Jupyter, what is the output of `datacube products list`

**Comment by patrickmuston1** [comment]
fixed in commit [https://github.com/EY-Data-Science-Program/2020-bushfire-challenge/commit/0492b121464d451147b7250fde8ef769b8e10f46]
